server:
  port: 8081

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    open-in-view: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

